version: '3.8'

services:
  api:
    build: .
    image: panasonic_back_end
    deploy:
      replicas: 3
    ports:
      - "9000:9000"
    network_mode: host
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY={SECRET_KEY}
    env_file:
      - .env
    restart: always